spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNTSERVICE
          predicates:
            - Path=/accountservice/account/**
          filters:
            - name: JwtFilter
            - RewritePath=/accountservice/account/(?<segment>.*), /${segment}

        - id: transaction-service
          uri: lb://TRANSACTIONSERVICE
          predicates:
            - Path=/transaction/**
          filters:
            - name: JwtFilter
            - RewritePath=/transaction/(?<segment>.*), /${segment}

        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/notification/**
          filters:
            - name: JwtFilter
            - RewritePath=/notification/(?<segment>.*), /${segment}

      default-filters:
        - name: JwtFilter

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${HOSTNAME:localhost}
